"""fixed table bug

Revision ID: 72d2559341b6
Revises: 7a78916e2088
Create Date: 2021-01-18 16:36:13.901244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d2559341b6'
down_revision = '7a78916e2088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_list', schema=None) as batch_op:
        batch_op.drop_index('ix_book_list_author')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=25), nullable=True))
        batch_op.create_index('ix_book_list_author', ['author'], unique=False)

    # ### end Alembic commands ###
