"""added author

Revision ID: 7a78916e2088
Revises: 
Create Date: 2021-01-18 16:30:07.243119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a78916e2088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_name'), ['name'], unique=False)

    op.create_table('book_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booktitle', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('startdate', sa.DateTime(timezone='%Y-%m-%d'), nullable=True),
    sa.Column('author', sa.String(length=25), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_list_author'), ['author'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_list_author'))

    op.drop_table('book_list')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_name'))

    op.drop_table('author')
    # ### end Alembic commands ###
