"""adding date  migration

Revision ID: 506d48ebd06e
Revises: 3ddbf2226d28
Create Date: 2020-11-04 13:27:52.070504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d48ebd06e'
down_revision = '3ddbf2226d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do_list', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('to_do_list', 'deadline')
    # ### end Alembic commands ###
